# This action run e2e test for pull requests
name: test-real-e2e
on: [pull_request]
jobs:
  e2e-mysql:
    strategy:
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    services:
      db:
        image: mysql:8.0.26
        env:
          MYSQL_DATABASE: lake
          MYSQL_USER: merico
          MYSQL_PASSWORD: merico
          MYSQL_ROOT_PASSWORD: root
    container: mericodev/lake-builder:0.0.4
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        env:
          DB_URL: root:root@tcp(db:3306)/lake?charset=utf8mb4&loc=Asia%2fShanghai&parseTime=True
        run: |
          cp .env.example .env
          docker-compose up -f docker-compose.test.yml
          make real-e2e-test
